//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscountsYourWay
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityQuestion
    {
        public int SecurityQuestionID { get; set; }
        public string SecurityQuestion1 { get; set; }
    }
}
